2024-12-11 10:14:38,011 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Домашний\PycharmProjects\pythonProject\module_12\tests_12_4.py", line 7, in test_walk
    print(Runner('Вася', -5))
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Домашний\PycharmProjects\pythonProject\module_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
2024-12-11 10:14:38,017 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Домашний\PycharmProjects\pythonProject\module_12\tests_12_4.py", line 14, in test_run
    print(Runner(1, 2))
          ^^^^^^^^^^^^
  File "C:\Users\Домашний\PycharmProjects\pythonProject\module_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
